name: BuildAndPackage

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: write

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17

      - name: Build using Maven
        run: mvn -B clean package

      - name: Update and push CHANGELOG
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          # 这里可以执行你的更新 CHANGELOG 逻辑，比如脚本自动更新 CHANGELOG.md
          git add CHANGELOG.md
          git commit -m "chore: update CHANGELOG [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main

      - name: Read version from pom.xml
        id: get_version
        # 通过 mvn 命令解析 pom.xml 中的 project.version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          body: |
            **自动发布**  
            版本：${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
