name: Generate Changelog

permissions:
  contents: write

on:
  push:
    # 只在 Tag 名称是数字.数字 (例如: 1.6, 1.7, 2.0 等) 或数字.数字.数字 时触发工作流
    tags:
      - '[0-9]*.[0-9]*'
      - '[0-9]*.[0-9]*.[0-9]*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Conventional Changelog CLI
        run: npm install -g conventional-changelog-cli

      - name: Generate Changelog
        # 这里采用 angular preset，你也可以使用其他预设，比如 conventionalcommits、atom 等
        run: |
          # 如果你本地已有 CHANGELOG.md，可以先保留它
          # 后续再次生成时会自动追加，不会覆盖原有内容
          conventional-changelog -p angular -i CHANGELOG.md -s -r 0

      - name: Commit and push changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          # 先还原对 .github/workflows/xxx.yml 的任何修改，防止它被提交
          git restore .github/workflows/xxx.yml
          
          # 只将 CHANGELOG.md 添加到提交
          git add CHANGELOG.md
          
          # 提交并推送
          git commit -m "chore: update CHANGELOG [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main
