name: BuildAndPackage

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: write

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1.9

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # 或者你需要的版本

      - name: Install conventional-changelog-cli
        run: npm install -g conventional-changelog-cli

      - name: Generate/Update CHANGELOG.md
        run: |
          # 这里假设你用的是 Angular Preset，可自行根据需求更改
          conventional-changelog -p angular -i CHANGELOG.md -s
          
          # 这里 -p angular 表示使用 Angular 风格的 Preset
          # -i 指定要生成或更新的文件
          # -s 表示在原文件上直接修改（in-place）
      
      - name: Commit and push CHANGELOG updates
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          git add CHANGELOG.md
          git commit -m "chore: update CHANGELOG [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main
