name: Build and Package Java Application

on:
  push:
    branches:
      - main  # Trigger on push to main branch

env:
  PKG_NAME: jtreesize
  MAIN_CLASS: org.ligson.jtreesize.App

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]  # Run on all three platforms
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21 and Maven Cache
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"  # Use Eclipse Temurin distribution
          java-version: "21"
          cache: "maven"

      - name: Extract Version from POM (Windows)
        if: runner.os == 'Windows'
        id: get-version-windows
        run: |
          $version = (mvn help:evaluate '-Dexpression=project.version' -q -DforceStdout)
          echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Extract Version from POM (Linux and macOS)
        if: runner.os != 'Windows'
        id: get-version-linux-macos
        run: |
          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          version=$(echo $version | xargs)  # Trim any leading/trailing spaces
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean package '-Dmaven.test.skip=true'

      - name: Prepare Output Directory
        run: mkdir -p dist

      - name: Extract Packaged Archive
        run: |
          tar -zxvf target/${{ env.PKG_NAME }}-${{ env.VERSION }}-${{ env.PKG_NAME }}.tar.gz -C target/ 

      - name: Install WiX
        if: runner.os == 'Windows'
        run: dotnet tool install --global wix

      - name: Package Application with jpackage (Windows)
        if: runner.os == 'Windows'
        run: |
          jpackage `
            --input . `
            --name ${{ env.PKG_NAME }} `
            --main-jar lib/${{ env.PKG_NAME }}-${{ env.VERSION }}.jar `
            --main-class ${{ env.MAIN_CLASS }} `
            --type exe `
            --resource-dir conf `
            --icon conf/treesize.ico `
            --win-dir-chooser `
            --win-shortcut `
            --app-version ${{ env.VERSION }}
          mv ${{ env.PKG_NAME }}-${{ env.VERSION }}.exe ../../dist/
        working-directory: target/${{ env.PKG_NAME }}-${{ env.VERSION }}

      - name: Package Application with jpackage (Non-Windows)
        if: runner.os == 'macOS'
        run: |
          jpackage \
            --input . \
            --name ${{ env.PKG_NAME }} \
            --main-jar lib/${{ env.PKG_NAME }}-${{ env.VERSION }}.jar \
            --main-class ${{ env.MAIN_CLASS }} \
            --type dmg \
            --resource-dir conf \
            --icon conf/treesize.icns \
            --app-version ${{ env.VERSION }}
          mv ${{ env.PKG_NAME }}-${{ env.VERSION }}.dmg ../../dist/
        working-directory: target/${{ env.PKG_NAME }}-${{ env.VERSION }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PKG_NAME }}-${{ env.VERSION }}-${{ matrix.os }}
          path: dist/

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/${{ env.PKG_NAME }}-${{ env.VERSION }}-${{ matrix.os }}.exe
          asset_name: ${{ env.PKG_NAME }}-${{ env.VERSION }}-${{ matrix.os }}.exe
          asset_content_type: application/vnd.microsoft.portable-executable
