name: Generate Changelog

on:
  push:
    # 只在 Tag 名称是数字.数字 (例如: 1.6, 1.7, 2.0 等) 时触发工作流
    tags:
      - '[0-9]*.[0-9]*'
      - '[0-9]*.[0-9]*.[0-9]*'  # 如果还有可能用到三段式(1.6.1)的版本号，可以加上这条

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # 必须要有 write 权限，才能推送到仓库

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Conventional Changelog CLI
        run: npm install -g conventional-changelog-cli

      - name: Generate Changelog
        # 这里采用angular预设，你也可以用其他preset
        run: |
          # 如果你本地已经有CHANGELOG.md，可以先保留，后续生成时自动追加
          # conventional-changelog -p angular -i CHANGELOG.md -s
          conventional-changelog -p angular -i CHANGELOG.md -s

      - name: Commit and push changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "chore: update CHANGELOG [skip ci]" || echo "No changes to commit"
          git push
